version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./:/app
    command: php -S 0.0.0.0:8000 -t /app
    ports:
      - "8000:8000"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: isbulnet
    ports:
      - "3306:3306"
